# Generated by Django 5.2.1 on 2025-05-24 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0002_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas/'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente de Pagamento'), ('Recebido', 'Pedido Recebido'), ('Em Preparo', 'Em Preparo'), ('Pronto para Entrega', 'Pronto para Entrega'), ('Em Rota', 'Em Rota de Entrega'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado'), ('Retirada', 'Pronto para Retirada')], default='Recebido', max_length=50)),
                ('tipo_entrega', models.CharField(choices=[('Entrega', 'Entrega em Domicílio'), ('Delivery', 'Entrega Delivery')], default='Entrega', max_length=50)),
                ('endereco_entrega_formatado', models.TextField(blank=True, null=True)),
                ('subtotal_itens', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_entrega_aplicada', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('desconto_aplicado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Cartao Credito', 'Cartão de Crédito'), ('Cartao Debito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Dinheiro', 'Dinheiro')], max_length=50, null=True)),
                ('troco_para', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_pronto', models.DateTimeField(blank=True, null=True)),
                ('data_saiu_para_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_entregue_ou_retirado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pizzaria.cliente')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='pizzaria.motoboy')),
            ],
            options={
                'ordering': ['data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario_momento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaria.bebida')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaria.pizza')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pizzaria.pedido')),
            ],
        ),
    ]
