# Generated by Django 5.2.1 on 2025-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_bebida_imagem_pizza_imagem_pizza_ingredientes_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='doc_moto',
            field=models.ImageField(blank=True, null=True, upload_to='cnhs/'),
        ),
    ]
