# Generated by Django 5.2.1 on 2025-05-24 18:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0004_remove_motoboy_endereco_alter_motoboy_doc_moto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do cupom (ex: PROMO10)', max_length=50, unique=True)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, help_text='Desconto em porcentagem (ex: 10 para 10%)', max_digits=5)),
                ('data_validade', models.DateTimeField(help_text='Data e hora em que o cupom expira')),
                ('ativo', models.BooleanField(default=True, help_text='Cupom está ativo e pode ser usado?')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='desconto_aplicado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerenciados', to='pizzaria.funcionario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_desconto_cupom',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='tamanho',
            field=models.CharField(choices=[('latinha', 'Latinha (350ml)'), ('600ml', '600ML'), ('1l', '1L'), ('1.5l', '1.5L'), ('2l', '2L')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motoboy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('Entrega', 'Entrega em Domicílio'), ('Retirada', 'Retirada no Local')], default='Entrega', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamanho',
            field=models.CharField(choices=[('pequena', 'Pequena'), ('media', 'Média'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_com_cupom', to='pizzaria.cupom'),
        ),
    ]
