# Generated by Django 5.2.1 on 2025-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0005_cupom_remove_pedido_desconto_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='placa_moto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_validade',
            field=models.DateField(help_text='Data em que o cupom expira'),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='doc_moto',
            field=models.ImageField(blank=True, null=True, upload_to='doc_motos/'),
        ),
    ]
