# Generated by Django 5.2.1 on 2025-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0006_motoboy_placa_moto_alter_cupom_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxaentrega',
            options={'ordering': ['distancia_max_km']},
        ),
        migrations.RemoveField(
            model_name='taxaentrega',
            name='local',
        ),
        migrations.AddField(
            model_name='taxaentrega',
            name='descricao',
            field=models.CharField(default='Taxa Genérica', help_text='Descrição da faixa (Ex: Até 3km)', max_length=100),
        ),
        migrations.AddField(
            model_name='taxaentrega',
            name='distancia_max_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
