# Generated by Django 5.2.1 on 2025-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0007_alter_taxaentrega_options_remove_taxaentrega_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxaentrega',
            name='distancia_max_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, unique=True),
        ),
    ]
