# Generated by Django 5.2.1 on 2025-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0008_alter_taxaentrega_distancia_max_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxaentrega',
            name='descricao',
            field=models.CharField(help_text='Descrição da faixa (Ex: Entrega Padrão até 3km)', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxaentrega',
            name='distancia_max_km',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Distância MÁXIMA (em Km) coberta por esta taxa. Ex: 3.00', max_digits=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxaentrega',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do frete para esta faixa de distância. Ex: 5.00', max_digits=6),
        ),
    ]
